In [1]:
my_list = [1,2,3,4]

In [2]:
my_list


[1, 2, 3, 4]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr


array([1, 2, 3, 4])

In [7]:
 my_mat = [[1,2,3],[4,5,6],[7,8,9]]
    

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)


array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [18]:
np.random.rand(5,5)

array([[0.29173864, 0.20738332, 0.05591206, 0.73164999, 0.27059652],
       [0.31770358, 0.407467  , 0.00809669, 0.54686251, 0.51567178],
       [0.18355748, 0.79681808, 0.09720047, 0.43204273, 0.67819991],
       [0.52633801, 0.93715314, 0.32401865, 0.09619012, 0.18987458],
       [0.34916218, 0.06986687, 0.2999821 , 0.78349149, 0.67071949]])

In [24]:
np.random.randn(2,1)

array([[ 1.81888662],
       [-0.82860995]])

In [37]:
arr = np.random.randint(0,50,25)

In [38]:
arr.reshape(5,5)

array([[47, 37,  3,  0,  6],
       [18, 23, 26, 32, 15],
       [37, 37, 10, 11, 22],
       [49,  9, 48, 47, 14],
       [36,  3, 42, 30,  7]])

In [40]:
arr.reshape(25)

array([47, 37,  3,  0,  6, 18, 23, 26, 32, 15, 37, 37, 10, 11, 22, 49,  9,
       48, 47, 14, 36,  3, 42, 30,  7])

In [41]:
 arr.max()

49

In [42]:
arr.min()

0

In [43]:
arr.argmax()

15

In [44]:
arr.argmin()

3

In [45]:
arr.shape

(25,)

In [47]:
arr.reshape(5,5).shape

(5, 5)

In [48]:
arr.dtype

dtype('int32')