In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
arr.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[0:5] = 100 

In [12]:
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(11)

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
slice_of_arr = arr[:5]

In [22]:
slice_of_arr[:] = 99 
arr = np.arange(11)

In [23]:
slice_of_arr = arr[:5].copy()

In [24]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[0][0]

5

In [41]:
arr_2d[:,1]

array([10, 25, 40])

In [43]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [44]:
arr = np.arange(11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
boo_arr = arr > 1

In [48]:
arr[boo_arr]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr[arr < 3]

array([0, 1, 2])

In [51]:
arr_2d = np.arange(50).reshape(5,10)

In [52]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [56]:
arr_2d[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [58]:
arr_2d[1:3,:5]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])